# --- CULTIVOS ---
SUPERFICIE_PINO = 2.0
AGUA_INICIAL_PINO = 2
ALTURA_INICIAL_ARBOL = 1.0

SUPERFICIE_OLIVO = 3.0
AGUA_INICIAL_OLIVO = 5

SUPERFICIE_LECHUGA = 0.10
AGUA_INICIAL_LECHUGA = 1

SUPERFICIE_ZANAHORIA = 0.15
AGUA_INICIAL_ZANAHORIA = 0

# --- RIEGO ---
INTERVALO_SENSOR_TEMPERATURA = 2.0
SENSOR_TEMP_MIN = -25
SENSOR_TEMP_MAX = 50

INTERVALO_SENSOR_HUMEDAD = 3.0
SENSOR_HUMEDAD_MIN = 0
SENSOR_HUMEDAD_MAX = 100

TEMP_MIN_RIEGO = 8
TEMP_MAX_RIEGO = 15
HUMEDAD_MAX_RIEGO = 50
INTERVALO_CONTROL_RIEGO = 2.5
THREAD_JOIN_TIMEOUT = 2.0

# --- STRATEGY (Absorción) ---
ABSORCION_SEASONAL_VERANO = 5
ABSORCION_SEASONAL_INVIERNO = 2
MES_INICIO_VERANO = 3
MES_FIN_VERANO = 8

# --- PERSISTENCIA ---
DIRECTORIO_DATA = "data"
EXTENSION_DATA = ".dat"
